### ISSUE TITLE
Metadata/header?

### ISSUE THREAD

**Issue by NogginBops** [SpaceKrakens/SKON#14]
In discussion the idea that SKON should have a way to define extra data like version and schema location in either a header or some metadata notation.

The initial syntax suggestion was to use the `~` symbol to indicate metadata.
It would look like this:

```
~Version: 0.1~
~Schema: "./SomeSchema.skema"~
~CustomMetadata: "Should this be allowed."~

ActualData: "This is not metadata"
```

Another question is if there should be user defined metadata?

**Comment by Dormanil** [comment]
Well, what could the parser do with custom metadata? What kinds of metadata should be allowed? 

Or would custom metadata be just bloat at the beginning of the file, intended for the user to signify things, but doesn't do anything while parsing? If so, custom metadata would just be glorified comments, and I am against those.

**Comment by NogginBops** [comment]
The idea with custom metadata is that a user can check this data before parsing and take appropriate actions accordingly. One could imagine having document versions that look different and require different parsing. This would be easier with custom metadata. 

Otherwise I think that a version and schema header is a good idea. It would be a good way to define schema location and SKON version. This is somewhat important to be able to change the syntax in the future without breaking a lot of parsers.
