### ISSUE TITLE
Should arrays be limited to just one type?

### ISSUE THREAD

**Issue by NogginBops** [SpaceKrakens/SKON#15]
Right now the specification is limiting all array elements to be of the same datatype. Inferred from the first type.

Should this restriction be removed? The restriction could be moved to schema so that you in a schema could restrict the type of an array.

A slightly related question would be if array should be renamed to list as that could possibly be a better description.

**Comment by Dormanil** [comment]
While yes, in our current code, SKONObject arrays can hold all kinds of SKONObjects, I personally find this restriction makes sense. 
A SKON array converts to a C# array, while the SKON map is more used like an object. Arrays and lists can hold only values of one type, but objects can hold anything they want, and I'd like to keep it that way.
